SYSTEM1_INGEST_TASK_NAME = "ingest-system1"
SYSTEM1_INGEST_DEBOUNCE_SECONDS = 300.0
SUMMARIZE_MEMORY_TASK_NAME = "summarize-memory"
PROJECT_MANAGER_TASK_NAME = "project-manager"
FACT_CHECKER_TASK_NAME = "fact-checker"
GRAPH_LINKER_TASK_NAME = "graph-linker"
CONFLICT_DETECTOR_TASK_NAME = "conflict-detector"
DEFRAGMENTER_TASK_NAME = "defragmenter"
DEDUPLICATOR_TASK_NAME = "deduplicator"
TAXONOMIST_TASK_NAME = "taxonomist"
SWEEPER_TASK_NAME = "sweeper"
MAINTENANCE_TASK_NAMES = (
	PROJECT_MANAGER_TASK_NAME,
	FACT_CHECKER_TASK_NAME,
	GRAPH_LINKER_TASK_NAME,
	CONFLICT_DETECTOR_TASK_NAME,
	DEFRAGMENTER_TASK_NAME,
	DEDUPLICATOR_TASK_NAME,
	TAXONOMIST_TASK_NAME,
	SWEEPER_TASK_NAME,
)
TRIGGERABLE_BACKGROUND_TASK_NAMES = (
	SYSTEM1_INGEST_TASK_NAME,
	*MAINTENANCE_TASK_NAMES,
)
SYSTEM1_INGEST_THRESHOLD = 10
DEFAULT_INGEST_BATCH_SIZE = 20
DEFAULT_SWEEP_RETENTION_DAYS = 7
DEFAULT_STALE_PLAN_DAYS = 60
DEFAULT_AGENT_SCAN_LIMIT = 50
DEFAULT_RECURRING_TASK_INTERVAL_SECONDS = 300.0
RECURRING_TASK_INTERVAL_SECONDS = {
	PROJECT_MANAGER_TASK_NAME: 600.0,
	FACT_CHECKER_TASK_NAME: DEFAULT_RECURRING_TASK_INTERVAL_SECONDS,
	GRAPH_LINKER_TASK_NAME: 3600.0,
	CONFLICT_DETECTOR_TASK_NAME: 3600.0,
	DEFRAGMENTER_TASK_NAME: 3600.0,
	DEDUPLICATOR_TASK_NAME: 3600.0,
	TAXONOMIST_TASK_NAME: 3600.0,
	SWEEPER_TASK_NAME: 21600.0,
}