SYSTEM1_INGEST_TASK_NAME = "ingest-system1"
SYSTEM1_INGEST_DEBOUNCE_SECONDS = 1800.0
SUMMARIZE_MEMORY_TASK_NAME = "summarize-memory"
PROJECT_MANAGER_TASK_NAME = "project-manager"
FACT_CHECKER_TASK_NAME = "fact-checker"
GRAPH_LINKER_TASK_NAME = "graph-linker"
CONFLICT_DETECTOR_TASK_NAME = "conflict-detector"
DEFRAGMENTER_TASK_NAME = "defragmenter"
DEDUPLICATOR_TASK_NAME = "deduplicator"
TAXONOMIST_TASK_NAME = "taxonomist"
SWEEPER_TASK_NAME = "sweeper"
CURATOR_TASK_NAME = "memory-curator"
MAINTENANCE_TASK_NAMES = (
	PROJECT_MANAGER_TASK_NAME,
	FACT_CHECKER_TASK_NAME,
	GRAPH_LINKER_TASK_NAME,
	CONFLICT_DETECTOR_TASK_NAME,
	DEFRAGMENTER_TASK_NAME,
	DEDUPLICATOR_TASK_NAME,
	TAXONOMIST_TASK_NAME,
	SWEEPER_TASK_NAME,
	CURATOR_TASK_NAME,
)
TRIGGERABLE_BACKGROUND_TASK_NAMES = (
	SYSTEM1_INGEST_TASK_NAME,
	*MAINTENANCE_TASK_NAMES,
)
SYSTEM1_INGEST_THRESHOLD = 20
DEFAULT_INGEST_BATCH_SIZE = 20
DEFAULT_SWEEP_RETENTION_DAYS = 7
DEFAULT_STALE_PLAN_DAYS = 60
DEFAULT_AGENT_SCAN_LIMIT = 50
SYSTEM1_INGEST_PRIORITY = 10
SUMMARIZE_MEMORY_PRIORITY = 20
PROJECT_MANAGER_PRIORITY = 40
FACT_CHECKER_PRIORITY = 45
GRAPH_LINKER_PRIORITY = 60
CONFLICT_DETECTOR_PRIORITY = 60
TAXONOMIST_PRIORITY = 60
DEFRAGMENTER_PRIORITY = 70
DEDUPLICATOR_PRIORITY = 70
SWEEPER_PRIORITY = 90
CURATOR_PRIORITY = 95
DEFAULT_TASK_PRIORITY = 100
DEFAULT_RECURRING_TASK_INTERVAL_SECONDS = 300.0
RECURRING_TASK_INTERVAL_SECONDS = {
	PROJECT_MANAGER_TASK_NAME: 600.0,
	FACT_CHECKER_TASK_NAME: DEFAULT_RECURRING_TASK_INTERVAL_SECONDS,
	GRAPH_LINKER_TASK_NAME: 3600.0,
	CONFLICT_DETECTOR_TASK_NAME: 3600.0,
	DEFRAGMENTER_TASK_NAME: 3600.0,
	DEDUPLICATOR_TASK_NAME: 7200.0,
	TAXONOMIST_TASK_NAME: 3600.0,
	SWEEPER_TASK_NAME: 21600.0,
	CURATOR_TASK_NAME: 21600.0,
}

TASK_PRIORITIES = {
	SYSTEM1_INGEST_TASK_NAME: SYSTEM1_INGEST_PRIORITY,
	SUMMARIZE_MEMORY_TASK_NAME: SUMMARIZE_MEMORY_PRIORITY,
	PROJECT_MANAGER_TASK_NAME: PROJECT_MANAGER_PRIORITY,
	FACT_CHECKER_TASK_NAME: FACT_CHECKER_PRIORITY,
	GRAPH_LINKER_TASK_NAME: GRAPH_LINKER_PRIORITY,
	CONFLICT_DETECTOR_TASK_NAME: CONFLICT_DETECTOR_PRIORITY,
	TAXONOMIST_TASK_NAME: TAXONOMIST_PRIORITY,
	DEFRAGMENTER_TASK_NAME: DEFRAGMENTER_PRIORITY,
	DEDUPLICATOR_TASK_NAME: DEDUPLICATOR_PRIORITY,
	SWEEPER_TASK_NAME: SWEEPER_PRIORITY,
	CURATOR_TASK_NAME: CURATOR_PRIORITY,
}


def task_priority(task_name: str) -> int:
	return TASK_PRIORITIES.get(task_name, DEFAULT_TASK_PRIORITY)
