from __future__ import annotations

from typing import Generic, Protocol, TypeVar


ConnectionT_co = TypeVar("ConnectionT_co", covariant=True)
ConnectionT = TypeVar("ConnectionT")


class CursorLike(Protocol):
    def __enter__(self) -> CursorLike: ...

    def __exit__(self, exc_type, exc, tb) -> bool | None: ...

    def execute(self, query: str, params: tuple[object, ...] | None = None) -> object: ...

    def executemany(self, query: str, rows: list[tuple[object, ...]]) -> object: ...

    def fetchone(self) -> tuple[object, ...] | None: ...

    def fetchall(self) -> list[tuple[object, ...]]: ...


class DbConnectionLike(Protocol):
    def cursor(self) -> CursorLike: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...


class PoolLike(Protocol, Generic[ConnectionT]):
    def getconn(self) -> ConnectionT: ...

    def putconn(self, connection: ConnectionT) -> None: ...

    def close(self) -> None: ...


class ConnectionLease(Protocol, Generic[ConnectionT_co]):
    def __enter__(self) -> ConnectionT_co: ...

    def __exit__(self, exc_type, exc, tb) -> bool | None: ...

    def close(self) -> None: ...


class SessionManager(Protocol, Generic[ConnectionT_co]):
    def __enter__(self) -> SessionManager[ConnectionT_co]: ...

    def __exit__(self, exc_type, exc, tb) -> bool | None: ...

    def open_connection(self) -> ConnectionLease[ConnectionT_co]: ...

    def close(self) -> None: ...