from __future__ import annotations


PROJECT_MANAGER_TASK_NAME = "project-manager"
FACT_CHECKER_TASK_NAME = "fact-checker"
GRAPH_LINKER_TASK_NAME = "graph-linker"
CONFLICT_DETECTOR_TASK_NAME = "conflict-detector"
DEFRAGMENTER_TASK_NAME = "defragmenter"
DEDUPLICATOR_TASK_NAME = "deduplicator"
TAXONOMIST_TASK_NAME = "taxonomist"
SWEEPER_TASK_NAME = "sweeper"
CURATOR_TASK_NAME = "memory-curator"

MAINTENANCE_TASK_NAMES = (
    PROJECT_MANAGER_TASK_NAME,
    FACT_CHECKER_TASK_NAME,
    GRAPH_LINKER_TASK_NAME,
    CONFLICT_DETECTOR_TASK_NAME,
    DEFRAGMENTER_TASK_NAME,
    DEDUPLICATOR_TASK_NAME,
    TAXONOMIST_TASK_NAME,
    SWEEPER_TASK_NAME,
    CURATOR_TASK_NAME,
)

DEFAULT_RECURRING_TASK_INTERVAL_SECONDS = 300.0

RECURRING_TASK_INTERVAL_SECONDS = {
    PROJECT_MANAGER_TASK_NAME: 600.0,
    FACT_CHECKER_TASK_NAME: DEFAULT_RECURRING_TASK_INTERVAL_SECONDS,
    GRAPH_LINKER_TASK_NAME: 3600.0,
    CONFLICT_DETECTOR_TASK_NAME: 3600.0,
    DEFRAGMENTER_TASK_NAME: 21600.0,
    DEDUPLICATOR_TASK_NAME: 7200.0,
    TAXONOMIST_TASK_NAME: 3600.0,
    SWEEPER_TASK_NAME: 21600.0,
    CURATOR_TASK_NAME: 3600.0,
}